name = "openguard-website"
account_id = "f97093bac8d84a0eb995c9c7f40bf984"
zone_id = "f97093bac8d84a0eb995c9c7f40bf984"
route = "openguard.lol/*"
workers_dev = false
compatibility_date = "2024-04-05"
main = "dist/_worker.js"
